apiVersion: apps/v1
kind: Deployment
metadata:
  name: cylinder
  namespace: cylinder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cylinder
  template:
    metadata:
      name: cylinder
      namespace: cylinder
      labels:
        app: cylinder
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: topology.kubernetes.io/zone
                operator: In
                values:
                - "1"
      tolerations:
        - key: node.kubernetes.io/memory-pressure
          operator: Exists
      containers:
      - name: cylinder
        image: quay.io/rh_ee_sfairchi/stress:latest
