apiVersion: apps/v1
kind: Deployment
metadata:
  name: barracuda
  namespace: barracuda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: barracuda
  template:
    metadata:
      name: barracuda
      namespace: barracuda
      labels:
        app: barracuda
    spec:
      # affinity:
        # nodeAffinity:
          # requiredDuringSchedulingIgnoredDuringExecution:
            # nodeSelectorTerms:
            # - matchExpressions:
              # - key: topology.kubernetes.io/zone
                # operator: In
                # values:
                # - "eastus-1"
      tolerations:
        - key: node.kubernetes.io/memory-pressure
          operator: Exists
      containers:
      - name: barracuda
        image: quay.io/rh_ee_sfairchi/stress:latest
