apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress
  namespace: stress
spec:
  replicas: 3
  selector:
    matchLabels:
      app: stress
  template:
    metadata:
      name: stress
      namespace: stress
      labels:
        app: stress
    spec:
      tolerations:
        - key: node.kubernetes.io/memory-pressure
          operator: Exists
      containers:
      - name: stress-tmpfs
        image: docker.io/progrium/stress
        args:
        - --io
        - "50"
        - --hdd
        - "150"
        - --hdd-noclean
        - --verbose
        volumeMounts:
        - name: database
          mountPath: /database
        workingDir: /database
      volumes:
      - name: database
        emptyDir:
          medium: Memory
          