apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress
  namespace: stress
spec:
  replicas: 40
  selector:
    matchLabels:
      app: stress
  template:
    metadata:
      name: stress
      namespace: stress
      labels:
        app: stress
    spec:
      tolerations:
        - key: node.kubernetes.io/memory-pressure
          operator: Exists
      containers:
      - name: stress
        image: docker.io/polinux/stress
        imagePullPolicy: IfNotPresent
        args:
        - --vm
        - "10"
        - --vm-keep
        - --verbose
